# Generated by Django 4.0 on 2021-12-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfload',
            old_name='createdDatwe',
            new_name='createdDate',
        ),
    ]
