# Generated by Django 4.0 on 2021-12-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_createddatwe_pdfload_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapdf',
            name='department',
        ),
        migrations.RemoveField(
            model_name='datapdf',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='datapdf',
            name='jury1',
        ),
        migrations.RemoveField(
            model_name='datapdf',
            name='jury2',
        ),
        migrations.RemoveField(
            model_name='datapdf',
            name='university',
        ),
        migrations.AddField(
            model_name='datapdf',
            name='juries',
            field=models.TextField(null=True, verbose_name='Juri Bilgileri'),
        ),
        migrations.AddField(
            model_name='datapdf',
            name='okul',
            field=models.TextField(null=True, verbose_name='Okul'),
        ),
    ]
